### PR TITLE
BLUI-4717: added 9 new icons

### LINKED ISSUE #308: Unable to run React demo
#### Describe the bug / expected behavior

The screen is blank. The console displays the error message `Uncaught Error: useNavigate() may be used only in the context of a <Router> component.`

This happens on dev branch

#### What are the steps to reproduce?

1. Git clone
2. from project root, run: `yarn install && yarn build && yarn start`

#### Screenshots / Screen recording

image

#### Your environment information

- node v20.11.0
- yarn v3.3.0
- macOS 14.2.1 (23C71)
- chrome 121.0.6167.184

### PR DESCRIPTION
**Pull request by huayunh**
Fixes BLUI-4717, fixes #308 

## Changes proposed in this Pull Request:

- Added 9 new icons: Ethernet Port, Skillet, Skillet Cooktop, Cooking, Stockpot, Stove, Wind Turbine, Water Energy, IOT Scene.
- Replaced Tom with Ekta in the code owners.

## Screenshots / Screen Recording (if applicable)

image

## To Test:

- Verify that all the icon files have been correctly generated for each package (SVG, mui, PNG, rn-vector, icon font)
- `yarn && yarn start`
- **fixed now** ~Normally you would do yarn start. But for some reason `yarn start` does not work on my machine (#308)~

### CODE REVIEW

**Comment by ektaghag-eaton** [comment]
I am also getting same error mentioned [here](https://github.com/etn-ccis/blui-icons/issues/308).

**Comment by joebochill** [comment]
See the fix for the issue here: https://github.com/etn-ccis/blui-icons/issues/308#issuecomment-1943783013

**Comment by joebochill** [comment]
Your branch will run after you bump the react-router dependency versions and then run:

`yarn install && yarn build && yarn update:demo && yarn start`

`update:demo` makes sure that the demo project is updated to use the newest version of the packages you create when you build them.

**Comment by huayunh** [comment]
It worked! Let me ensure to capture that in the readme.

**Comment by ektaghag-eaton** [comment]
Able to see mentioned icons under /mui and /font 👍 .

SVG shows the below icons only. Is it correct? 
Screenshot 2024-02-15 at 11 07 34 AM

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
