### PR TITLE
Add 33 new icons

### PR DESCRIPTION
**Pull request by huayunh**
~I need technical help! I cannot seem to make my new icons show up in the demo projects!~ Fixed now

#### New icons added

Pliers, Screwdriver, Box Cutter, Hammer, Home Repair Service Outline, TV Remote, Angular, React, GitHub, Database, Bolt Off, PPE Level, PPE Level Two Tone, Multimeter, Multimeter Outline, Blast, Arc Rated Hood, Balaclava, Overalls, Arc Rated Suit, Glove, Glove Alt, Insulated Glove, Insulated Glove Alt, Left Outline, Right Outline, Left, Right, Double Triangle, Screw Head Slotted, Screw Head Phillips, Heat Shrink Tube, Hard Hat

image

### CODE REVIEW

**Comment by joebochill** [comment]
To get the icons to show in the demo, you'll need to make sure that the versions in the package.json of the demo will match the versions in the package.json of the icon packages. It looks like neither have been updated in this PR.

**Comment by joebochill** [comment]
I would also strongly recommend against putting two tones icons in the package...they will not work at all as an icon font. I think we'll probably want to consider setting up a different package if we want to have a library of two-tones.

**Comment by huayunh** [comment]
I have updated all the package json version numbers, but the icons are still not showing up?

**Comment by huayunh** [comment]
(patching some final small corners...)

**Comment by JeffGreiner-eaton** [comment]
I verified the new icons and had questions. is bolt_off correct name? or should it be volt_off
is the ppe_levels correct name? or should it be ippe_levels? just checking...
One more thing, we have 3 two_tones in here, are we leaving them in?

**Comment by huayunh** [comment]
- Bolt off and PPE level are both correct names.
- I have written a story (BLUI-3881) for two tone related stuff. They need to be left there for now.
- 391 file changes for 32 new icons are correct.

**Review by JeffGreiner-eaton — APPROVED** [review]
seems good to me

**Pull request merged**
